export const ADMIN_LOGIN_DETAILS_REQUEST = "ADMIN_LOGIN_DETAILS_REQUEST";
export const ADMIN_LOGIN_DETAILS_SUCCESS = "ADMIN_LOGIN_DETAILS_SUCCESS";
export const ADMIN_LOGIN_DETAILS_FAIL = "ADMIN_LOGIN_DETAILS_FAIL";

export const ADMIN_REQUEST_VERIFICATION_CODE =
	"ADMIN_REQUEST_VERIFICATION_CODE";
