export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_VERIFICATION_REQUEST = "ADMIN_VERIFICATION_REQUEST";
export const ADMIN_VERIFICATION_SUCCESS = "ADMIN_VERIFICATION_SUCCESS";
export const ADMIN_VERIFICATION_FAIL = "ADMIN_VERIFICATION_FAIL";

export const ADMIN_SIGNOUT = "ADMIN_SIGNOUT";

export const ADMIN_TOKEN_EXPIRED = "ADMIN_TOKEN_EXPIRED";

export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST";
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS";
export const ADMIN_ADD_PRODUCT_FAIL = "ADMIN_ADD_PRODUCT_FAIL";

export const ADMIN_GET_PRODUCT_REQUEST = "ADMIN_GET_PRODUCT_REQUEST";
export const ADMIN_GET_PRODUCT_SUCCESS = "ADMIN_GET_PRODUCT_SUCCESS";
export const ADMIN_GET_PRODUCT_FAIL = "ADMIN_GET_PRODUCT_FAIL";

export const ADMIN_GET_ONE_PRODUCT_REQUEST = "ADMIN_GET_ONE_PRODUCT_REQUEST";
export const ADMIN_GET_ONE_PRODUCT_SUCCESS = "ADMIN_GET_ONE_PRODUCT_SUCCESS";
export const ADMIN_GET_ONE_PRODUCT_FAIL = "ADMIN_GET_ONE_PRODUCT_FAIL";

export const ADMIN_INVALID_TOKEN = "ADMIN_INVALID_TOKEN";

export const ADMIN_GET_IMAGE_REQUEST = "ADMIN_GET_IMAGE_REQUEST";
export const ADMIN_GET_IMAGE_FAIL = "ADMIN_GET_IMAGE_FAIL";
export const ADMIN_GET_IMAGE_SUCCESS = "ADMIN_GET_IMAGE_SUCCESS";
export const ADMIN_UPLOAD_IMAGE_SUCCESS = "ADMIN_UPLOAD_IMAGE_SUCCESS";
