export const ADD_TO_CART_ITEM = "ADD_TO_CART_ITEM";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CART_SAVE_SHIPPING_DETAILS = "CART_SAVE_SHIPPING_DETAILS";
export const CART_PAYMENT = "CART_PAYMENT";
export const CART_EMPTY = "CART_EMPTY";
