export const SEND_ENQUIRY_REQUEST = "SEND_ENQUIRY_REQUEST";
export const SEND_ENQUIRY_SUCCESS = "SEND_ENQUIRY_SUCCESS";
export const SEND_ENQUIRY_FAIL = "SEND_ENQUIRY_FAIL";

export const SEND_BOOKING_REQUEST = "SEND_BOOKING_REQUEST";
export const SEND_BOOKING_SUCCESS = "SEND_BOOKING_SUCCESS";
export const SEND_BOOKING_FAIL = "SEND_BOOKING_FAIL";

export const GET_ENQUIRY_REQUEST = "GET_ENQUIRY_REQUEST";
export const GET_ENQUIRY_SUCCESS = "GET_ENQUIRY_SUCCESS";
export const GET_ENQUIRY_FAIL = "GET_ENQUIRY_FAIL";

export const GET_BOOKING_REQUEST = "GET_BOOKING_REQUEST";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAIL = "GET_BOOKING_FAIL";

export const GET_ONE_ENQUIRY_REQUEST = "GET_ONE_ENQUIRY_REQUEST";
export const GET_ONE_ENQUIRY_SUCCESS = "GET_ONE_ENQUIRY_SUCCESS";
export const GET_ONE_ENQUIRY_FAIL = "GET_ONE_ENQUIRY_FAIL";

export const GET_ONE_BOOKING_REQUEST = "GET_ONE_BOOKING_REQUEST";
export const GET_ONE_BOOKING_SUCCESS = "GET_ONE_BOOKING_SUCCESS";
export const GET_ONE_BOOKING_FAIL = "GET_ONE_BOOKING_FAIL";
