export const SUBMIT_CONTACT_US_REQUEST = "SUBMIT_CONTACT_US_REQUEST";
export const SUBMIT_CONTACT_US_SUCCESS = "SUBMIT_CONTACT_US_SUCCESS";
export const SUBMIT_CONTACT_US_FAIL = "SUBMIT_CONTACT_US_FAIL";
